aws-samples/generative-ai-cdk-constructs-samples

samples/document_explorer/setup_client_app.py
=> fix: update example password to follow policy

samples/document_explorer/bin/document_explorer.ts
=> feat(doc explorer): add metrics tracking code to stack description

README.md, samples/bedrock-agent/.gitignore, samples/bedrock-agent/.npmignore, samples/bedrock-agent/README.md, samples/bedrock-agent/bin/bedrock-agent.ts, samples/bedrock-agent/cdk.json, samples/bedrock-agent/jest.config.js, samples/bedrock-agent/lib/bedrock-agent-stack.ts, samples/bedrock-agent/package.json, samples/bedrock-agent/pnpm-lock.yaml, samples/bedrock-agent/scripts/load-kb.sh, samples/bedrock-agent/test/bedrock-agent.test.ts, samples/bedrock-agent/tsconfig.json
Add a new sample: This sample provides a sample application which deploys a Bedrock Agent and Knowledge Base backed by an OpenSearch Serverless Collection and documents in S3. It demonstrates how to use https://github.com/awslabs/generative-ai-cdk-constructs/pull/207.
=> feat(samples): new sample application (Bedrock agent)

samples/document_explorer/README.md, samples/document_explorer/bin/document_explorer.ts, samples/document_explorer/lib/api-stack.ts, samples/document_explorer/lib/networking-stack.ts, samples/document_explorer/lib/persistence-stack.ts, samples/document_explorer/package-lock.json, samples/document_explorer/package.json
Added support for OpenSearch Serverless in Doc Explorer sample
---
=> feat: Added support for OpenSearch Serverless in Doc Explorer sample

samples/document_explorer/client_app/pages/1_📁_Select_Document.py, samples/document_explorer/client_app/pages/2_🏷️_Summary.py, samples/document_explorer/client_app/pages/3_💬_Q&A.py, samples/document_explorer/client_app/requirements.txt
This PR includes the following changes:
- Removes extraneous page switching when a file is selected to improve file selection user experience (feat)
- Removes switch_page_button from Summary and Q&A pages to streamline navigation based on user feedback (feat) 
- Updates requirements.txt with latest dependencies to ensure compatibility (chore)
---
=> feat: improve file selection ux and streamline navigation

samples/sagemaker_jumpstart_model/README.md, samples/sagemaker_jumpstart_model/lib/sagemaker_jumpstart_model-stack.ts, samples/sagemaker_jumpstart_model/package-lock.json, samples/sagemaker_jumpstart_model/package.json
=> chore(construct): update to latest lib version

samples/bedrock-agent/package-lock.json, samples/bedrock-agent/package.json, samples/bedrock-agent/scripts/load-kb.sh
*Description of changes:* update sample to include fix provided in https://github.com/awslabs/generative-ai-cdk-constructs/pull/350
=> chore(deps): update deps to include fix preventing deployment of kb

samples/document_explorer/client_app/pages/3_Q&A.py, samples/document_explorer/client_app/pages/4_Summary.py
1. Added max_doc in Q&A side bar.
2. updated summary text area size. 
=> feat(docexplorer): UI changes

samples/document_explorer/package.json
updated generative-ai-cdk-version to **0.1.107** to support latest construct changes for document explorer
=> feat(libversion) : updated generative-ai-cdk-version to 0.1.107

samples/bedrock-agent/README.md, samples/content-generation/README.md, samples/document_explorer/README.md, samples/sagemaker_custom_endpoint/README.md, samples/sagemaker_huggingface_inferentia/README.md, samples/sagemaker_huggingface_model/README.md, samples/sagemaker_huggingface_model_llava/README.md
Propagate previous PR to other samples 
=> chore(doc): update readme to add install instructions

samples/bedrock-agent/package-lock.json, samples/bedrock-agent/package.json
update package version to latest available one
=> chore(deps): update package version

samples/bedrock-agent/package-lock.json, samples/bedrock-agent/package.json
*Description of changes:* update bedrock sample to use the latest version of the constructs library
=> chore(bedrock): update sample with latest version to access latest model

samples/document_explorer/client_app/pages/3_Q&A.py, samples/document_explorer/client_app/pages/4_Summary.py, samples/document_explorer/package-lock.json, samples/document_explorer/package.json
… fix bug
update constructs dependency to use the latest version available, add support for premier, and fix a bug where filename was not sent as part of the request for long context
=> chore(update): update doc explorer sample

samples/bedrock-agent/lib/bedrock-agent-stack.ts, samples/bedrock-agent/package-lock.json, samples/bedrock-agent/package.json
=> chore(sample): update sample to latest version of the library

samples/document_explorer/package-lock.json, samples/document_explorer/package.json
=> chore(deps): update doc explorer to latest version

samples/sagemaker_custom_endpoint/package-lock.json, samples/sagemaker_custom_endpoint/package.json
Update sagemaker custom endpoint sample
=> chore(deps): update custom sample

samples/image-description/package.json
=> Update package.json aws-cdk-lib version

samples/image-description/client_app/pages/image_description.py, samples/image-description/lib/image-description-stack.ts
Updated image-summarization sample model_id options to filter based on selected modality. 
=> feat(image-description): updated sample for blog feedback

samples/bedrock-agent/package-lock.json, samples/bedrock-agent/package.json
=> chore(deps): update bedrock agent deps to latest version

samples/image-description/bin/image-description.ts, samples/image-description/client_app/Home.py, samples/image-description/client_app/common/cognito_helper.py, samples/image-description/client_app/graphql/graphql_mutation_client.py, samples/image-description/client_app/pages/image_description.py, samples/image-description/lib/image-description-stack.ts
1. Updated formatting
2. Added documentation
3. Added usb key
=> feat(sample): updated documentation, formatting

samples/image-description/README.md, samples/image-description/bin/image-description.ts, samples/image-description/lib/image-description-stack.ts
1. formatting and documentation
=> feat(sample): formatting and documentation

samples/document_explorer/lib/networking-stack.ts
*VPC example should include the services that package communicates to enable private subnet. If not gen-ai-cdk-construct will create.*
=> chore: add vpc endpoints

samples/image-description/client_app/.streamlit/config.toml, samples/image-description/client_app/pages/image_description.py
Changed file uploader default limit  from 200 to 1 MB
=> feat(image-description): changed file uploader default limit

samples/bedrock-agent/package-lock.json, samples/bedrock-agent/package.json, samples/bedrock-web-crawler/package-lock.json, samples/bedrock-web-crawler/package.json, samples/sagemaker_custom_endpoint/package-lock.json, samples/sagemaker_custom_endpoint/package.json, samples/sagemaker_huggingface_model/package-lock.json, samples/sagemaker_huggingface_model/package.json
Fix dependabot issues related to cdk version:
- https://github.com/aws-samples/generative-ai-cdk-constructs-samples/security/dependabot/34
- https://github.com/aws-samples/generative-ai-cdk-constructs-samples/security/dependabot/33
- https://github.com/aws-samples/generative-ai-cdk-constructs-samples/security/dependabot/32
- https://github.com/aws-samples/generative-ai-cdk-constructs-samples/security/dependabot/31
=> chore(deps): fix cdk dependabot issues

samples/text-to-sql/README.md, samples/text-to-sql/package-lock.json
=> fix(cdk): fix dependabot issue on cdk version in text-to-sql

samples/document_explorer/lib/networking-stack.ts
=> chore(vpc): add missing vpc endpoints for latest version

samples/document_explorer/README.md, samples/document_explorer/terraform-config-frontend/main.tf, samples/document_explorer/terraform-config-frontend/terraform.tfvars, samples/document_explorer/terraform-config-frontend/variables.tf
Removing hard coded region from frontend terraform deployment and adding region variable. 
=> fix: adding region as fe var

samples/bedrock-agent/package-lock.json, samples/bedrock-agent/package.json, samples/content-generation/package-lock.json, samples/content-generation/package.json, samples/document_explorer/README.md, samples/document_explorer/lib/networking-stack.ts, samples/document_explorer/package-lock.json, samples/document_explorer/package.json, samples/image-description/client_app/requirements.txt, samples/image-description/package-lock.json, samples/image-description/package.json
Tested:
-  all workflows in the doc explorer and fix the issue of not working subscription feedback to the frontend
- image description anf fix a missing package in requirement.txt for the streamlit app
- bedrock agent
- content gen
=> fix(sample): fix missing subscription feedback

samples/python-samples/python_samples/opensearch_vectorindex.py
Added I am role to deploy opensearch vector index in python-samples
=> feat(pythonsample): fixed vector index mapping issue

samples/document_explorer/client_app/Home.py, samples/document_explorer/multi-doc-mod/lambda/aws-qa-custom/question_answering/src/requirements.txt, samples/document_explorer/package-lock.json, samples/document_explorer/package.json
=> chore(deps): fix dependabot issues

samples/contract-compliance-analysis/front-end/package-lock.json, samples/contract-compliance-analysis/front-end/tailwind.config.js
=> Replace module.exports with export; fix npm audit issues

samples/contract-compliance-analysis/back-end/stack/sfn/__init__.py, samples/contract-compliance-analysis/back-end/stack_constructs/lambda_constructs.py
=> Narrow down CloudWatch permissions on Lambda functions

samples/bedrock-agent/lib/bedrock-agent-stack.ts, samples/bedrock-agent/package-lock.json, samples/bedrock-agent/package.json
*Description of changes:* Update sample following breaking changes introduced in version 0.1.290 of the constructs library.
=> chore(bedrock_agent): update sample with latest version

samples/content-generation/README.md, samples/document_explorer/README.md, samples/image-description/README.md, samples/llamaindex-basic-data-loader/README.md, samples/text-to-sql/README.md
Add a deprecation banner to samples which will be deprecated soon:
=> chore(doc): announce deprecation of some samples

samples/bedrock-agent/lib/bedrock-agent-stack.ts, samples/bedrock-agent/package-lock.json, samples/bedrock-agent/package.json
*Description of changes:* Update sample to latest version
=> chore(deps): update deps

samples/contract-compliance-analysis/back-end/README.md, samples/contract-compliance-analysis/back-end/app_properties.yaml, samples/contract-compliance-analysis/back-end/stack/sfn/common-layer/llm.py, samples/contract-compliance-analysis/back-end/stack/sfn/common-layer/requirements.txt
=> Use Cross-region Inference; Retry request in case of Bedrock throttling

samples/contract-compliance-analysis/back-end/app.py, samples/multimodal-rag/backend/app.py, samples/python-samples/python_samples/bedrock_opensearch_stack.py, samples/python-samples/python_samples/prompt_management.py, samples/rfp-answer-generation/backend/app.py, samples/rfp-answer-generation/backend/stack/inference_stack.py, samples/rfp-answer-generation/backend/stack/ingestion_stack.py, samples/sagemaker_custom_endpoint/lib/sagemaker_custom_endpoint-stack.ts, samples/sagemaker_huggingface_inferentia/lib/sagemaker_huggingface_inferentia-stack.ts, samples/sagemaker_huggingface_model/lib/sagemaker_huggingface_model-stack.ts, samples/sagemaker_huggingface_model_llava/lib/sagemaker_huggingface_model_llava-stack.ts, samples/sagemaker_huggingface_model_svd/lib/sagemaker_huggingface_model_svd-stack.ts, samples/sagemaker_jumpstart_model/lib/sagemaker_jumpstart_model-stack.ts
=> chore(tags): update tags

samples/mcp-stateless-lambda/.gitignore, samples/mcp-stateless-lambda/README.md, samples/mcp-stateless-lambda/lambdas/authorizer/index.js, samples/mcp-stateless-lambda/lambdas/mcpserver/index.js, samples/mcp-stateless-lambda/lambdas/mcpserver/logging.js, samples/mcp-stateless-lambda/lambdas/mcpserver/mcp-errors.js, samples/mcp-stateless-lambda/lambdas/mcpserver/mcp-server.js, samples/mcp-stateless-lambda/lambdas/mcpserver/metadata.js, samples/mcp-stateless-lambda/lambdas/mcpserver/transport.js, samples/mcp-stateless-lambda/mcp_client/index.js, samples/mcp-stateless-lambda/package-lock.json, samples/mcp-stateless-lambda/package.json
=> chore(lambda-mcp): add missing files

samples/bedrock-data-automation/.gitignore, samples/content-generation/.gitignore, samples/document_explorer/.gitignore, samples/image-description/.gitignore, samples/speech-to-speech/README.md
=> chore(doc): remove deprecated folders
